# Generated by Django 5.0.6 on 2024-05-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО утв.')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Утверждающие',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Подрядные организации',
            },
        ),
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер по генплану')),
                ('construction', models.CharField(blank=True, max_length=255, verbose_name='Наименование здания, сооружения')),
                ('installation', models.CharField(blank=True, max_length=255, verbose_name='Установка')),
                ('short', models.CharField(blank=True, max_length=255, verbose_name='Краткое обозначение установки')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Наименование объекта')),
            ],
            options={
                'verbose_name_plural': 'Поз. по генплану',
            },
        ),
        migrations.CreateModel(
            name='Kait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Работники КАиТ',
                'ordering': ('-job_title',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Мастера цеха',
            },
        ),
        migrations.CreateModel(
            name='Kip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='№ п/п')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Заводской номер')),
                ('defective_act', models.CharField(blank=True, max_length=255, verbose_name='№ дефектного акта')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='ТЭГ')),
                ('type', models.CharField(blank=True, max_length=255, verbose_name='Тип')),
                ('name_of_equipment', models.TextField(blank=True, verbose_name='Наименование оборуования')),
                ('equipment_acceptance_date_PNR', models.CharField(blank=True, max_length=255, verbose_name='Дата приемки оборудования в ПНР')),
                ('equipment_manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель оборудования')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='Проект')),
                ('date_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_of_detection', models.CharField(blank=True, max_length=255, verbose_name='Дата выявления')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='Место установки')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание дефекта')),
                ('reasons_for_failure', models.TextField(blank=True, verbose_name='Возможные причины выхода из строя')),
                ('elimination_of_defects', models.CharField(blank=True, max_length=255, verbose_name='Для устранения выявленных дефектов необходимо')),
                ('operating_time', models.CharField(blank=True, max_length=255, verbose_name='Время наработки, ч')),
                ('approval_date', models.CharField(blank=True, max_length=255, verbose_name='Дата утверждения')),
                ('number_letter_INVEST', models.CharField(blank=True, max_length=255, verbose_name='№ исходящего письма')),
                ('letter_to_INVEST', models.CharField(blank=True, max_length=255, verbose_name='Дата отправки письма в Инвест')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место нахождения')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('fio_locksmith_1', models.CharField(blank=True, max_length=255, verbose_name='ФИО слесаря')),
                ('fio_locksmith_2', models.CharField(blank=True, max_length=255, verbose_name='ФИО слесаря')),
                ('elimination_date', models.CharField(blank=True, max_length=255, verbose_name='Дата устранения')),
                ('fio_responsible', models.CharField(blank=True, max_length=255, verbose_name='ФИО отв.')),
                ('mark_of_elimination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отметка об устранении')),
                ('executor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kaits', to='equipment.kait', verbose_name='ФИО Исполнителя 1')),
                ('executor_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractors', to='equipment.contractor', verbose_name='ФИО Исполнителя 3')),
                ('person_approving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approves', to='equipment.approve', verbose_name='ФИО утвеждающего')),
                ('poz_GP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gps', to='equipment.gp', verbose_name='Поз. по ГП')),
                ('executor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workers', to='equipment.worker', verbose_name='ФИО Исполнителя 2')),
            ],
            options={
                'verbose_name_plural': 'Оборудование КИП',
                'ordering': ('-date_at',),
            },
        ),
    ]
